import type {
  AgentOpportunity,
  DomainDefinition,
  EvidenceSource,
} from "./types";

export const domains: DomainDefinition[] = [
  {
    id: "discovery",
    label: "Discovery",
    shortLabel: "Discovery",
    descriptor: "From scientific question to testable hypothesis",
    workflows: ["Literature intelligence", "Target assessment", "Experiment planning"],
    frictions: [
      "Evidence is fragmented across papers and internal knowledge",
      "Teams repeatedly reconstruct the same scientific context",
      "Weak and contradicting evidence is easy to miss",
    ],
    dataCharacteristics: "Public literature, assay results, internal research notes",
    humanDecision: "Scientists judge biological plausibility and choose what to test.",
  },
  {
    id: "preclinical",
    label: "Preclinical",
    shortLabel: "Preclinical",
    descriptor: "Turn candidate evidence into development decisions",
    workflows: ["Study design", "Safety evidence review", "Translational assessment"],
    frictions: [
      "Study evidence arrives in incompatible formats",
      "Rationale and assumptions lose traceability",
      "Cross-study comparison requires specialist review",
    ],
    dataCharacteristics: "Study reports, lab systems, images, structured endpoints",
    humanDecision: "Study leaders validate interpretation and determine progression.",
  },
  {
    id: "clinical",
    label: "Clinical Development",
    shortLabel: "Clinical",
    descriptor: "Design and run trials with fewer avoidable inconsistencies",
    workflows: ["Protocol design", "Trial intelligence", "Site support"],
    frictions: [
      "Complex protocols contain inconsistent definitions and references",
      "Amendments propagate slowly across trial operations",
      "Site questions create repeated manual interpretation work",
    ],
    dataCharacteristics: "Protocols, trial registries, site queries, operational metrics",
    humanDecision: "Clinical and regulatory experts validate every material finding.",
  },
  {
    id: "regulatory",
    label: "Regulatory",
    shortLabel: "Regulatory",
    descriptor: "Maintain traceability as evidence and expectations change",
    workflows: ["Regulatory intelligence", "Submission readiness", "Response coordination"],
    frictions: [
      "Guidance changes across jurisdictions",
      "Evidence gaps surface late in submission preparation",
      "Source-to-claim traceability is manually intensive",
    ],
    dataCharacteristics: "Guidance, correspondence, submission modules, evidence tables",
    humanDecision: "Regulatory owners determine interpretation and submission position.",
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    shortLabel: "Manufacturing",
    descriptor: "Investigate process signals without jumping to conclusions",
    workflows: ["Deviation triage", "Process troubleshooting", "Batch knowledge retrieval"],
    frictions: [
      "Signals are distributed across equipment, records and operator notes",
      "Historical investigations are hard to reuse",
      "Investigators can anchor on an early root-cause theory",
    ],
    dataCharacteristics: "Batch records, time series, equipment logs, operator notes",
    humanDecision: "Qualified investigators and QA own root-cause determination.",
  },
  {
    id: "quality",
    label: "Quality",
    shortLabel: "Quality",
    descriptor: "Make quality knowledge usable and reviewable",
    workflows: ["CAPA analysis", "SOP navigation", "Inspection readiness"],
    frictions: [
      "Related quality events are difficult to connect",
      "Teams search large controlled-document estates manually",
      "Effectiveness checks lack consistent evidence views",
    ],
    dataCharacteristics: "QMS records, controlled documents, audit trails, training data",
    humanDecision: "Quality owners approve actions, classifications and closure.",
  },
  {
    id: "post-market",
    label: "Post-market",
    shortLabel: "Post-market",
    descriptor: "Monitor emerging signals with appropriate escalation",
    workflows: ["Safety surveillance", "Medical information", "Evidence monitoring"],
    frictions: [
      "Signal volume exceeds available review capacity",
      "Context is split across cases and external evidence",
      "Prioritisation must remain explainable and reviewable",
    ],
    dataCharacteristics: "Safety cases, literature, call records, structured product data",
    humanDecision: "Safety and medical teams assess signals and decide escalation.",
  },
];

export const opportunities: AgentOpportunity[] = [
  {
    id: "scientific-investigator",
    name: "Scientific Investigation Agent",
    domain: "discovery",
    workflow: "Structured evidence investigation",
    problem: "Scientists spend days reconstructing fragmented evidence before they can reason about what is known.",
    description: "Turns a biological question into a source-linked evidence workspace with claims, contradictions, limitations and knowledge gaps.",
    agentPattern: "Scientific Investigator",
    humanRole: "Scientist judges relevance, biological interpretation and which hypotheses deserve further investigation.",
    dataRequired: "Literature, biological databases, expression datasets and selected internal research records",
    value: 9,
    feasibility: 8,
    dataReadiness: 9,
    regulatoryExposure: 3,
    humanOversight: 9,
    decisionCriticality: 6,
    timeToValue: 8,
    status: "prototype",
    evidenceType: "hypothesis",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 10,
      dataAccessibility: 9,
      workflowRepeatability: 8,
      scientificJudgement: 9,
      toolIntegration: 6,
      evidenceTraceability: 10,
      reproducibilityBenefit: 8,
      operatingModel: "Scientist-supervised investigation agent",
    },
  },
  {
    id: "bioinformatics-investigator",
    name: "Bioinformatics Investigator",
    domain: "discovery",
    workflow: "Computational investigation",
    problem: "A biological question often stalls behind specialist tooling, pipeline setup and repeated hand-offs.",
    description: "Orchestrates a reviewable analysis workflow while pausing for scientist approval at biologically meaningful choices.",
    agentPattern: "Computational Operator",
    humanRole: "Scientists approve annotations, analytical choices and biological interpretation.",
    dataRequired: "Sequencing data, sample metadata, analysis environments, pathway databases and literature",
    value: 9,
    feasibility: 6,
    dataReadiness: 7,
    regulatoryExposure: 3,
    humanOversight: 10,
    decisionCriticality: 7,
    timeToValue: 6,
    status: "prototype",
    evidenceType: "hypothesis",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 10,
      dataAccessibility: 7,
      workflowRepeatability: 7,
      scientificJudgement: 10,
      toolIntegration: 9,
      evidenceTraceability: 9,
      reproducibilityBenefit: 10,
      operatingModel: "Scientist-approved computational operator",
    },
  },
  {
    id: "experiment-strategy",
    name: "Experiment Strategy Copilot",
    domain: "preclinical",
    workflow: "Experimental strategy exploration",
    problem: "Evidence, available techniques, controls and practical constraints are rarely compared in one place.",
    description: "Surfaces multiple experimental strategies and their trade-offs without selecting a supposedly correct experiment.",
    agentPattern: "Experimental Strategy Copilot",
    humanRole: "Scientist owns the experimental decision, protocol and safety assessment.",
    dataRequired: "Evidence workspace, available model systems, assay capabilities, prior experiments and constraints",
    value: 8,
    feasibility: 6,
    dataReadiness: 6,
    regulatoryExposure: 3,
    humanOversight: 10,
    decisionCriticality: 8,
    timeToValue: 6,
    status: "concept",
    evidenceType: "hypothesis",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 8,
      dataAccessibility: 6,
      workflowRepeatability: 6,
      scientificJudgement: 10,
      toolIntegration: 6,
      evidenceTraceability: 9,
      reproducibilityBenefit: 7,
      operatingModel: "Scientist-led strategy copilot",
    },
  },
  {
    id: "imaging-investigator",
    name: "Imaging Investigator",
    domain: "preclinical",
    workflow: "Scientific image analysis",
    problem: "Image-analysis choices and quality checks create friction between raw microscopy and interpretable phenotypes.",
    description: "Coordinates segmentation, feature extraction and phenotype exploration with explicit QC and uncertainty.",
    agentPattern: "Computational Operator",
    humanRole: "Imaging scientist validates segmentation quality and biological interpretation.",
    dataRequired: "Microscopy images, experimental metadata, segmentation tools and image-analysis models",
    value: 8,
    feasibility: 6,
    dataReadiness: 6,
    regulatoryExposure: 2,
    humanOversight: 9,
    decisionCriticality: 7,
    timeToValue: 6,
    status: "concept",
    evidenceType: "hypothesis",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 8,
      dataAccessibility: 6,
      workflowRepeatability: 8,
      scientificJudgement: 9,
      toolIntegration: 8,
      evidenceTraceability: 8,
      reproducibilityBenefit: 9,
      operatingModel: "Imaging-scientist-supervised operator",
    },
  },
  {
    id: "lab-memory",
    name: "Lab Memory Agent",
    domain: "discovery",
    workflow: "Institutional scientific memory",
    problem: "Troubleshooting knowledge is buried across ELNs, notebooks, instrument runs and research notes.",
    description: "Retrieves comparable experiments and recurring factors with source-level provenance.",
    agentPattern: "Institutional Memory",
    humanRole: "Researchers assess whether historical context is comparable and decide what to change.",
    dataRequired: "ELN records, protocols, samples, instrument runs, notebooks, reports and troubleshooting notes",
    value: 8,
    feasibility: 7,
    dataReadiness: 5,
    regulatoryExposure: 3,
    humanOversight: 8,
    decisionCriticality: 5,
    timeToValue: 7,
    status: "prototype",
    evidenceType: "inference",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 8,
      dataAccessibility: 5,
      workflowRepeatability: 9,
      scientificJudgement: 8,
      toolIntegration: 7,
      evidenceTraceability: 10,
      reproducibilityBenefit: 10,
      operatingModel: "Source-linked institutional memory",
    },
  },
  {
    id: "technology-scout",
    name: "Technology Scout",
    domain: "discovery",
    workflow: "Research technology scouting",
    problem: "Emerging scientific platforms are hard to compare across evidence, maturity and local infrastructure needs.",
    description: "Builds a traceable comparison of technologies that may be worth benchmarking over a defined horizon.",
    agentPattern: "Technology Scout",
    humanRole: "Research technology leaders define strategic fit and decide what, if anything, to benchmark.",
    dataRequired: "Papers, preprints, conferences, product documentation, benchmarks and local capability requirements",
    value: 7,
    feasibility: 7,
    dataReadiness: 8,
    regulatoryExposure: 2,
    humanOversight: 8,
    decisionCriticality: 6,
    timeToValue: 7,
    status: "concept",
    evidenceType: "inference",
    researchFocused: true,
    researchProfile: {
      researchLeverage: 7,
      dataAccessibility: 8,
      workflowRepeatability: 8,
      scientificJudgement: 8,
      toolIntegration: 5,
      evidenceTraceability: 9,
      reproducibilityBenefit: 6,
      operatingModel: "Research-technology decision support",
    },
  },
  {
    id: "knowledge-navigator",
    name: "Scientific Knowledge Navigator",
    domain: "discovery",
    workflow: "Research knowledge retrieval",
    problem: "Institutional knowledge is scattered and difficult to reuse.",
    description: "Retrieves source-linked scientific context across internal and public collections.",
    agentPattern: "Knowledge navigator",
    humanRole: "Scientists assess relevance and scientific validity.",
    dataRequired: "Document repositories, taxonomy, permissions",
    value: 8,
    feasibility: 7,
    dataReadiness: 6,
    regulatoryExposure: 3,
    humanOversight: 8,
    decisionCriticality: 5,
    timeToValue: 7,
    status: "concept",
    evidenceType: "inference",
  },
  {
    id: "experiment-planning",
    name: "Experiment Planning Copilot",
    domain: "preclinical",
    workflow: "Study planning",
    problem: "Design rationale and prior evidence are reconstructed manually.",
    description: "Surfaces comparable studies, assumptions and planning questions for scientist review.",
    agentPattern: "Decision-support copilot",
    humanRole: "Study director owns design and scientific decisions.",
    dataRequired: "Historical protocols, results, scientific constraints",
    value: 7,
    feasibility: 5,
    dataReadiness: 5,
    regulatoryExposure: 5,
    humanOversight: 9,
    decisionCriticality: 8,
    timeToValue: 5,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "protocol-guardian",
    name: "Protocol Guardian",
    domain: "clinical",
    workflow: "Protocol consistency review",
    problem: "Complex protocols create avoidable inconsistencies before downstream review.",
    description: "Reviews protocols for conflicting definitions, missing references and ambiguous terms.",
    agentPattern: "Reviewer",
    humanRole: "Clinical and regulatory expert validates every material finding.",
    dataRequired: "Protocol document, review rules, controlled terminology",
    value: 9,
    feasibility: 8,
    dataReadiness: 8,
    regulatoryExposure: 6,
    humanOversight: 9,
    decisionCriticality: 7,
    timeToValue: 9,
    status: "prototype",
    evidenceType: "hypothesis",
  },
  {
    id: "trial-intelligence",
    name: "Trial Intelligence Agent",
    domain: "clinical",
    workflow: "Competitive trial monitoring",
    problem: "Trial landscape changes are found late or lack context.",
    description: "Monitors trial registries and explains relevant changes against a defined portfolio.",
    agentPattern: "Monitor",
    humanRole: "Clinical strategy team judges relevance and response.",
    dataRequired: "Trial registries, portfolio context, monitoring criteria",
    value: 7,
    feasibility: 8,
    dataReadiness: 8,
    regulatoryExposure: 3,
    humanOversight: 7,
    decisionCriticality: 5,
    timeToValue: 8,
    status: "concept",
    evidenceType: "inference",
  },
  {
    id: "site-query-assistant",
    name: "Site Query Assistant",
    domain: "clinical",
    workflow: "Site support",
    problem: "Sites ask repeated questions whose answers require protocol interpretation.",
    description: "Drafts source-linked responses and routes ambiguous questions to trial experts.",
    agentPattern: "Workflow coordinator",
    humanRole: "Study team reviews material guidance before release.",
    dataRequired: "Approved protocol, FAQ history, study communications",
    value: 8,
    feasibility: 7,
    dataReadiness: 7,
    regulatoryExposure: 6,
    humanOversight: 9,
    decisionCriticality: 7,
    timeToValue: 8,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "regulatory-radar",
    name: "Regulatory Radar",
    domain: "regulatory",
    workflow: "Regulatory intelligence",
    problem: "Relevant changes across markets are monitored through fragmented processes.",
    description: "Monitors defined sources, classifies changes and proposes impacted areas for review.",
    agentPattern: "Monitor",
    humanRole: "Regulatory experts interpret applicability and required action.",
    dataRequired: "Authority sources, product context, market taxonomy",
    value: 8,
    feasibility: 7,
    dataReadiness: 7,
    regulatoryExposure: 7,
    humanOversight: 9,
    decisionCriticality: 7,
    timeToValue: 7,
    status: "concept",
    evidenceType: "inference",
  },
  {
    id: "submission-readiness",
    name: "Submission Readiness Agent",
    domain: "regulatory",
    workflow: "Submission quality review",
    problem: "Missing evidence and inconsistent claims surface late.",
    description: "Maps submission requirements to available evidence and flags gaps for author review.",
    agentPattern: "Reviewer",
    humanRole: "Regulatory lead validates readiness and submission claims.",
    dataRequired: "Submission content, requirements, evidence library",
    value: 9,
    feasibility: 6,
    dataReadiness: 6,
    regulatoryExposure: 9,
    humanOversight: 10,
    decisionCriticality: 9,
    timeToValue: 6,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "deviation-investigator",
    name: "Deviation Investigator",
    domain: "manufacturing",
    workflow: "Manufacturing deviation investigation",
    problem: "Investigators manually reconstruct signals from multiple systems.",
    description: "Builds an evidence-linked causal investigation tree and recommends next checks.",
    agentPattern: "Investigator",
    humanRole: "Qualified investigation and QA teams determine root cause.",
    dataRequired: "Batch records, sensor data, SOPs, notes, deviation history",
    value: 9,
    feasibility: 6,
    dataReadiness: 5,
    regulatoryExposure: 8,
    humanOversight: 10,
    decisionCriticality: 9,
    timeToValue: 6,
    status: "prototype",
    evidenceType: "hypothesis",
  },
  {
    id: "process-knowledge",
    name: "Process Knowledge Agent",
    domain: "manufacturing",
    workflow: "Process troubleshooting",
    problem: "Operational knowledge is distributed across records and experienced staff.",
    description: "Retrieves comparable batches, process context and source-linked troubleshooting knowledge.",
    agentPattern: "Knowledge navigator",
    humanRole: "Process experts assess relevance and determine intervention.",
    dataRequired: "Process history, batch records, technical reports",
    value: 8,
    feasibility: 6,
    dataReadiness: 5,
    regulatoryExposure: 6,
    humanOversight: 9,
    decisionCriticality: 7,
    timeToValue: 6,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "capa-intelligence",
    name: "CAPA Intelligence Agent",
    domain: "quality",
    workflow: "CAPA analysis",
    problem: "Related events and recurring failure patterns are difficult to see.",
    description: "Connects quality events and surfaces recurrence patterns with evidence provenance.",
    agentPattern: "Investigator",
    humanRole: "Quality owners assess causality and approve corrective actions.",
    dataRequired: "QMS events, CAPA history, taxonomy, effectiveness checks",
    value: 9,
    feasibility: 6,
    dataReadiness: 6,
    regulatoryExposure: 8,
    humanOversight: 10,
    decisionCriticality: 9,
    timeToValue: 6,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "sop-knowledge",
    name: "SOP Knowledge Agent",
    domain: "quality",
    workflow: "Controlled document navigation",
    problem: "Finding the applicable procedure and version takes too long.",
    description: "Answers bounded process questions with version-aware source links and escalation.",
    agentPattern: "Knowledge navigator",
    humanRole: "Users verify applicability; document owners govern content.",
    dataRequired: "Controlled SOP repository, metadata, permissions",
    value: 7,
    feasibility: 8,
    dataReadiness: 7,
    regulatoryExposure: 6,
    humanOversight: 8,
    decisionCriticality: 6,
    timeToValue: 9,
    status: "concept",
    evidenceType: "inference",
  },
  {
    id: "scientific-evidence",
    name: "Scientific Evidence Agent",
    domain: "post-market",
    workflow: "Cross-functional evidence monitoring",
    problem: "Scientific claims and safety context evolve across disconnected sources.",
    description: "Maintains traceable evidence views for medical, safety and regulatory teams.",
    agentPattern: "Researcher",
    humanRole: "Domain experts validate evidence strength and downstream use.",
    dataRequired: "Literature, internal evidence, product taxonomy",
    value: 8,
    feasibility: 7,
    dataReadiness: 7,
    regulatoryExposure: 7,
    humanOversight: 9,
    decisionCriticality: 8,
    timeToValue: 7,
    status: "concept",
    evidenceType: "hypothesis",
  },
  {
    id: "autonomous-discovery",
    name: "Autonomous Drug Discovery",
    domain: "discovery",
    workflow: "End-to-end discovery",
    problem: "Discovery cycles are long, uncertain and resource-intensive.",
    description: "Aspirational closed-loop discovery across hypothesis, design and experimentation.",
    agentPattern: "Workflow coordinator",
    humanRole: "Scientific leadership retains all material portfolio and experiment decisions.",
    dataRequired: "Integrated multimodal R&D estate, lab automation, validated models",
    value: 10,
    feasibility: 2,
    dataReadiness: 2,
    regulatoryExposure: 8,
    humanOversight: 10,
    decisionCriticality: 10,
    timeToValue: 1,
    status: "concept",
    evidenceType: "hypothesis",
  },
];

export const evidenceSources: EvidenceSource[] = [
  {
    id: "source-01",
    title: "Workflow discovery interview pack",
    type: "hypothesis",
    note: "Placeholder for client interview evidence and observed workflow friction.",
    placeholder: true,
  },
  {
    id: "source-02",
    title: "Life-sciences agent opportunity scan",
    type: "inference",
    note: "Placeholder for a sourced market and workflow scan; no external claims are asserted here.",
    placeholder: true,
  },
  {
    id: "source-03",
    title: "Public regulatory and scientific references",
    type: "public-evidence",
    note: "Citation slot reserved for verified public sources in a future research pass.",
    placeholder: true,
  },
];

export const getOpportunity = (id: string) =>
  opportunities.find((opportunity) => opportunity.id === id) ?? opportunities[0];

export const getDomain = (id: DomainDefinition["id"]) =>
  domains.find((domain) => domain.id === id) ?? domains[0];
